import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import HttpBackend from 'i18next-http-backend';
import LanguageDetector from 'i18next-browser-languagedetector';

export const I18N_NAMESPACES = ['common', 'marketingStudio'];

const FALLBACK_LOCALES = ['en', 'de'];

/**
 * Loads /locales/languages.json (generated by Vite from each locale dir under public/locales).
 * New languages only need that folder plus common.json; rerun dev or build to refresh the manifest.
 */
export async function initI18n() {
  if (i18n.isInitialized) {
    return i18n;
  }

  let locales = [...FALLBACK_LOCALES];
  try {
    const res = await fetch('/locales/languages.json', { cache: 'no-store' });
    if (res.ok) {
      const data = await res.json();
      if (Array.isArray(data.locales) && data.locales.length > 0) {
        locales = data.locales;
      }
    }
  } catch {
    /* offline / first paint */
  }

  await i18n
    .use(HttpBackend)
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
      fallbackLng: 'en',
      supportedLngs: locales,
      ns: I18N_NAMESPACES,
      defaultNS: 'common',
      interpolation: {
        escapeValue: false,
      },
      backend: {
        loadPath: '/locales/{{lng}}/{{ns}}.json',
      },
      detection: {
        order: ['localStorage', 'navigator'],
        lookupLocalStorage: 'i18nextLng',
        caches: ['localStorage'],
      },
      react: {
        useSuspense: true,
      },
    });

  return i18n;
}

export default i18n;
